config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'tags#index'
  get 'tags/show/', to: "tags#show_tag"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :apparels
  resources :profiles, only: %i[new create]
  resources :votings, only: %i[index new create]
  resources :biotypes, only: %i[index]
end

app/models/apparel.rb
class Apparel < ApplicationRecord
  STYLES = ['Hipster', 'Sexy', 'Clássico', 'Esportivo Casual', 'Romântico', 'Minimalista']
  has_many :categories, dependent: :destroy
  has_one_attached :photo
  has_many :tags, through: :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :tag
  belongs_to :apparel
end

app/models/recomendation.rb
class Recomendation < ApplicationRecord
  belongs_to :apparel
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :categories
  has_many :recomendations
  has_many :apparels, through: :categories
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :votings
  has_many :recomendations
  has_one_attached :photo
end

app/models/voting.rb
class Voting < ApplicationRecord
  belongs_to :user
  belongs_to :apparel
end

app/controllers/apparels_controller.rb
class ApparelsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @tag = Tag.where(id: params[:tag_id])
    if @tag.present?
      @apparels = Apparel.joins(:categories)
                         .joins(:tags)
                         .where(
                          categories: { tag: @tag.first },
                          style: (current_user && current_user.style) ? current_user.style : Apparel::STYLES
                          ).uniq
    else
      @apparels = Apparel.all
    end
  end

  def show
    @apparel = Apparel.find(params[:id])
  end

  def new
    @apparel = Apparel.new
  end

  def create
    @apparel = Apparel.new(apparel_params)
    if @apparel.save
      @tags = Tag.find(params[:apparel][:tags])
      @tags.each do |tag|
        Category.create(apparel: @apparel, tag: tag)
      end
    end
    redirect_to apparels_path
  end

  def edit
    @apparel = Apparel.find(params[:id])
    @tags = @apparel.tags
  end

  def update
    if current_user.admin?
      @apparel = Apparel.find(params[:id])
      if @apparel.update(apparel_params)
        redirect_to apparels_path, notice: 'Successfully updated.'
      else
        render :edit
      end
    else
      redirect_to root_path, notice: 'No permition to edit.'
    end
  end

  def destroy
    @apparel = Apparel.find(params[:id])
    if current_user.admin
      @apparel.destroy
      redirect_to apparels_path
    else
      redirect_to root_path
    end
  end

  private

  def apparel_params
    params.require(:apparel).permit(:style, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

  def after_sign_up_path_for(resource)
    new_voting_path
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "sixty-secs.fun" }
  end
end

app/controllers/biotypes_controller.rb
class BiotypesController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = User.new
  end

  def create
    @profile = current_user
  end
end

app/controllers/recomendations_controller.rb
class RecomendationsController < ApplicationController

  def index
    @tags = Tag.where(category: "ocasião")
  end

  def new
    @references = Reference.new
  end

  def create
    @apparel = Apparel.new(apparel_params)
    if @apparel.save
      @tags = Tag.find(params[:apparel][:tags])
      @tags.each do |tag|
        Category.create(apparel: @apparel, tag: tag)
      end
    end
    redirect_to apparels_path
  end

  private

  def apparel_params
    params.require(:apparel).permit(:style, :photo)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    :new_voting
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @tags = Tag.where(category: "Ocasião")
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController

  def index
  end

  def new
    @voting = Voting.new
    voted_apparel_ids = current_user.votings.pluck(:apparel_id)
    disliked_styles = current_user.votings.where(like: false).map {|voting| voting.apparel.style }.uniq
    @apparel = Apparel.where.not(id: voted_apparel_ids).where.not(style: disliked_styles).sample
  end

  def create
    @voting = Voting.new
    apparel = Apparel.find(params[:apparel_id])
    like = params[:like] == 'true'
    @voting.user = current_user
    @voting.apparel = apparel
    @voting.like = like
    @voting.save

    # Verifica se o user deu like em 3 estilos iguais
    style_more_3_likes = current_user.votings
                                     .where(like: true)
                                     .map(&:apparel)
                                     .group_by(&:style)
                                     .select { |_k, v| v.count >= 3 }.first&.first

    # Verifica se o user deu dislike em todos menos 1 estilo
    disliked_styles = current_user.votings.where(like: false).map {|voting| voting.apparel.style }.uniq
    styles = Apparel.all.pluck(:style).uniq

    if style_more_3_likes.present?
      current_user.style = style_more_3_likes
      current_user.save
      redirect_to votings_path

    elsif styles.count - disliked_styles.count == 1
      style = (styles - disliked_styles).first
      current_user.style = style
      current_user.save
      redirect_to votings_path

    else
      redirect_to new_voting_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for?(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end

end

app/views/apparels/edit.html.erb
<%# = raise %>
<div class="container text-center mt-3">
  <h2 style="background-color: rgb(214, 246, 109)">EDITANDO UM LOOK...</h2>
  <%= simple_form_for @apparel do |f| %>
    <div class="form-look">

        <%= f.input :style, collection: Apparel::STYLES %>

        <%= f.input :tags, collection: Tag.all.map { |tag| ["#{tag.category} #{tag.content}", tag.id] }, input_html: { multiple: true, class: 'multiple-select select2' }, include_hidden: false %>

        <%= f.input :photo, as: :file %>

        <%= f.submit "SALVAR", class: 'btn btn-ghost mt-3' %>
    </div>
  <% end %>

</div>

app/views/apparels/index.html.erb
<div class="container text-center">
  <% if @tag.present? %>
    <h2 style="background-color: rgb(214, 246, 109)">Looks para <%= @tag.first.content  %></h2>
  <% else %>
    <h2 style="background-color: rgb(214, 246, 109)">Todos os LOOKS</h2>
  <% end %>


  <div class="container-card row m-3">
    <% @apparels.each do |apparel| %>
      <div class="card-look col-12 col-md-4 align-items-center p-2 mb-1 d-flex justify-content-between">
        <div class="card-photo align-items-center">
            <%= cl_image_tag apparel.photo.key, class: "card-img-top" if apparel.photo.attached? %>
       </div>
        <div class="tags">
          <% apparel.categories.each do |category| %>
            <div class="tag">
              <span class="tag-btn"><%= link_to category.tag.content, apparels_path(tag_id: category.tag.id)%></span>
            </div>
          <% end %>
        </div>
        <div class="btns-admin d-flex">
        <% if current_user && current_user.admin %>
          <p class="edit m-2"><%= link_to 'Edit', edit_apparel_path(apparel) %></p>
          <p class="delete m-2"><%= link_to 'Delete', apparel_path(apparel), method: :delete, data: { confirm: 'Are you sure?' }%></p>
        <% end %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/apparels/new.html.erb
<div class="container text-center mt-3">
  <h2 style="background-color: rgb(214, 246, 109)">CADASTRANDO UM NOVO LOOK...</h2>
  <%= simple_form_for @apparel do |f| %>
    <div class="form-look">

        <%= f.input :photo, as: :file %>

        <%= f.input :style, collection: Apparel::STYLES %>

        <%= f.input :tags, collection: Tag.all.map { |tag| ["#{tag.category} #{tag.content}", tag.id] }, input_html: { multiple: true, class: 'multiple-select select2' }, include_hidden: false %>


        <%= f.submit "SALVAR", class: 'btn btn-ghost mt-3' %>
    </div>
  <% end %>

</div>

app/views/biotypes/index.html.erb
<div class="container text-center carpusel mt-3 mb-3">

  <h2 class="match" style="background-color: rgb(214, 246, 109)">ENTENDA QUAL É O SEU BIOTIPO CORPORAL...</h2>


  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" <%= image_tag "biotipo1.png" %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= image_tag "biotipo2.png" %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= image_tag "biotipo3.png" %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= image_tag "biotipo4.png" %>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= image_tag "biotipo5.png" %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= meta_title %> </title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag asset_path('logo-mini.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%# unless request.path.match?(/[sign]/) %>
      <%= render 'shared/footer' %>
    <%# end %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= image_path("backg-home.png") %>);">


</div>

app/views/profiles/new.html.erb
<h1>Vamos definir seu estilo</h1>

<%= simple_form_for @profile, url: profiles_path, method: :post do |f| %>
<%= f.input :photo,
                as: :file,
                required: false,
                autofocus: true,
                input_html: { multiple: false } %>
<%= f.submit 'OK' %>
<%end%>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links d-inline">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="slogan">
    <h4>Entendemos seu <strong style="background-color: rgb(214, 246, 109)">estilo</strong> e economizamos seu <strong style="background-color: rgb(214, 246, 109)">tempo</strong>!</h4>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-sixty-secs">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <ul class="navbar-nav mr-auto">
    <% unless current_user %>
    <li class="nav-item"><strong>
      <%= link_to "ENTRAR", new_user_session_path, class: "nav-link" %>
    </strong></li>
    <li class="nav-item"><strong>
      <%= link_to "CADASTRE-SE", new_user_registration_path, class: "nav-link" %>
    </strong></li>
    <% else %>
    <li class="nav-item"><strong>
      <%= link_to "CONHEÇA SEU BIOTIPO", biotypes_path, class: "nav-link" %>
    </strong></li>
    <% end %>
  </ul>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if current_user %>
        <li class="nav-item dropdown mr-4">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, transformation: [{width: 55, height: 55, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 55, crop: "scale"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else  %>
            <%= image_tag 'bearhat.jpg', transformation: [{width: 55, height: 55, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 55, crop: "scale"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Biotipos", "#", class: "dropdown-item" %>
            <% if current_user.admin %>
              <%= link_to "Cadastro de Looks", new_apparel_path, class: "dropdown-item" %>
            <% end %>
             <%# if current_user && current_user.style.blank? %>
              <%#= link_to "Defina seu estilo", new_voting_path, class: "dropdown-item" %>
            <%# end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>

    </ul>
  </div>
</div>

app/views/tags/index.html.erb
<div class="banner" style="background-image: url(<%= image_path("backg-home.png") %>);">

  <div class="home-cards">
    <h3 class="text-md-left mt-5 ml-5 ml6">
      <span class="letters">Qual a ocasião?</span>
    </h3>

    <div class="tag-container">
      <% @tags.each do |tag| %>
          <div class="occasions">
            <p> <%= link_to tag.content, apparels_path(tag_id: tag.id)%></p>
          </div>
      <% end %>
    </div>
  </div>

</div>

app/views/votings/index.html.erb
<div class="container text-center">


  <div class="banner-gif mt-4 mb-3" style="background-image: url(<%= image_path("banner-gif.gif") %>);">
    <h2 class="match" style="background-color: rgb(214, 246, 109)">IT'S A MATCH!<br>MAPEAMOS SEU ESTILO!</h2>
  </div>

  <div class="check d-flex justify-content-center mt-4 mb-3">
    <p>AGORA SUA EXPERIÊNCIA SERÁ PERSONALIZADA 😍</p>
  </div>

  <div class="check d-flex justify-content-center mt-4 mb-4">
    <p class="btn-check"><%= link_to 'ESCOLHA A OCASIÃO 👗', root_path %></p>
  </div>

</div>

app/views/votings/new.html.erb
<div class="container text-center">

  <h2 class="title-tinder">HORA DO TINDER DA MODA 👗 💘 👠 </h2>
  <h4 class="subtitle">Agora vamos mapear seu estilo! Quais LOOKS você usaria?</h4><br>

  <div class="card-tinder d-flex justify-content-center mb-3">
    <div class="photo-tinder">
      <%= cl_image_tag @apparel.photo.key %>
    </div>

    <div class="likes-tinder">
      <ul>
        <li> <%= link_to votings_path(like: true, apparel_id: @apparel.id), method: :post do%>
        <i class="far fa-thumbs-up"></i>
        <% end %> </li> <br><br>

        <li>  <%= link_to votings_path(like: false, apparel_id: @apparel.id), method: :post do%>
        <i class="far fa-thumbs-down"></i>
      <% end %> </li>
      </ul>




    </div>

    <% if current_user.admin %>
      <h4 class="subtitle"><%= @apparel.style%></h4>
    <% end %>

  </div>

</div>